/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AppUserEventResponse
 */
export interface AppUserEventResponse {
  /**
   *
   * @type {string}
   * @memberof AppUserEventResponse
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof AppUserEventResponse
   */
  firstName: string;
  /**
   *
   * @type {string}
   * @memberof AppUserEventResponse
   */
  lastName: string;
  /**
   *
   * @type {string}
   * @memberof AppUserEventResponse
   */
  major: string;
  /**
   *
   * @type {number}
   * @memberof AppUserEventResponse
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof AppUserEventResponse
   */
  role: AppUserEventResponseRoleEnum;
}

export function AppUserEventResponseFromJSON(json: any): AppUserEventResponse {
  return AppUserEventResponseFromJSONTyped(json, false);
}

export function AppUserEventResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AppUserEventResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json['email'],
    firstName: json['firstName'],
    lastName: json['lastName'],
    major: json['major'],
    id: json['id'],
    role: json['role'],
  };
}

export function AppUserEventResponseToJSON(
  value?: AppUserEventResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    firstName: value.firstName,
    lastName: value.lastName,
    major: value.major,
    id: value.id,
    role: value.role,
  };
}

/**
 * @export
 * @enum {string}
 */
export enum AppUserEventResponseRoleEnum {
  Admin = 'admin',
  Officer = 'officer',
  Member = 'member',
  Inductee = 'inductee',
  Guest = 'guest',
}
