/* tslint:disable */
/* eslint-disable */
/**
 * HKN API 
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppUserPKPayload
 */
export interface AppUserPKPayload {
    /**
     * 
     * @type {number}
     * @memberof AppUserPKPayload
     */
    id: number;
}

export function AppUserPKPayloadFromJSON(json: any): AppUserPKPayload {
    return AppUserPKPayloadFromJSONTyped(json, false);
}

export function AppUserPKPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppUserPKPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function AppUserPKPayloadToJSON(value?: AppUserPKPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


