/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AppUserInterviewAvailability
 */
export interface AppUserInterviewAvailability {
  /**
   *
   * @type {string}
   * @memberof AppUserInterviewAvailability
   */
  start: string;
  /**
   *
   * @type {string}
   * @memberof AppUserInterviewAvailability
   */
  end: string;
}

export function AppUserInterviewAvailabilityFromJSON(
  json: any
): AppUserInterviewAvailability {
  return AppUserInterviewAvailabilityFromJSONTyped(json, false);
}

export function AppUserInterviewAvailabilityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AppUserInterviewAvailability {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    start: json['start'],
    end: json['end'],
  };
}

export function AppUserInterviewAvailabilityToJSON(
  value?: AppUserInterviewAvailability | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    start: value.start,
    end: value.end,
  };
}
