/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AppUserMemberPointsResponse
 */
export interface AppUserMemberPointsResponse {
  /**
   *
   * @type {number}
   * @memberof AppUserMemberPointsResponse
   */
  user: number;
  /**
   *
   * @type {number}
   * @memberof AppUserMemberPointsResponse
   */
  points: number;
}

export function AppUserMemberPointsResponseFromJSON(
  json: any
): AppUserMemberPointsResponse {
  return AppUserMemberPointsResponseFromJSONTyped(json, false);
}

export function AppUserMemberPointsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AppUserMemberPointsResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    user: json['user'],
    points: json['points'],
  };
}

export function AppUserMemberPointsResponseToJSON(
  value?: AppUserMemberPointsResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user: value.user,
    points: value.points,
  };
}
