/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  AppUserInterviewAvailability,
  AppUserInterviewAvailabilityFromJSON,
  AppUserInterviewAvailabilityFromJSONTyped,
  AppUserInterviewAvailabilityToJSON,
} from './';

/**
 *
 * @export
 * @interface AppUserInterviewAvailabilitiesRequest
 */
export interface AppUserInterviewAvailabilitiesRequest {
  /**
   *
   * @type {Array<AppUserInterviewAvailability>}
   * @memberof AppUserInterviewAvailabilitiesRequest
   */
  availabilities: Array<AppUserInterviewAvailability>;
}

export function AppUserInterviewAvailabilitiesRequestFromJSON(
  json: any
): AppUserInterviewAvailabilitiesRequest {
  return AppUserInterviewAvailabilitiesRequestFromJSONTyped(json, false);
}

export function AppUserInterviewAvailabilitiesRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AppUserInterviewAvailabilitiesRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    availabilities: (json['availabilities'] as Array<any>).map(
      AppUserInterviewAvailabilityFromJSON
    ),
  };
}

export function AppUserInterviewAvailabilitiesRequestToJSON(
  value?: AppUserInterviewAvailabilitiesRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    availabilities: (value.availabilities as Array<any>).map(
      AppUserInterviewAvailabilityToJSON
    ),
  };
}
