/* tslint:disable */
/* eslint-disable */
/**
 * HKN API 
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AppUserInductionClass,
    AppUserInductionClassFromJSON,
    AppUserInductionClassFromJSONTyped,
    AppUserInductionClassToJSON,
} from './';

/**
 * 
 * @export
 * @interface AppUserProfileResponse
 */
export interface AppUserProfileResponse {
    /**
     * 
     * @type {string}
     * @memberof AppUserProfileResponse
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserProfileResponse
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserProfileResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserProfileResponse
     */
    major: string;
    /**
     * 
     * @type {string}
     * @memberof AppUserProfileResponse
     */
    graduationYear: string;
    /**
     * 
     * @type {AppUserInductionClass}
     * @memberof AppUserProfileResponse
     */
    inductionClass?: AppUserInductionClass;
    /**
     * 
     * @type {string}
     * @memberof AppUserProfileResponse
     */
    role: AppUserProfileResponseRoleEnum;
}

export function AppUserProfileResponseFromJSON(json: any): AppUserProfileResponse {
    return AppUserProfileResponseFromJSONTyped(json, false);
}

export function AppUserProfileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppUserProfileResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'email': json['email'],
        'major': json['major'],
        'graduationYear': json['graduationYear'],
        'inductionClass': !exists(json, 'inductionClass') ? undefined : AppUserInductionClassFromJSON(json['inductionClass']),
        'role': json['role'],
    };
}

export function AppUserProfileResponseToJSON(value?: AppUserProfileResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstName': value.firstName,
        'lastName': value.lastName,
        'email': value.email,
        'major': value.major,
        'graduationYear': value.graduationYear,
        'inductionClass': AppUserInductionClassToJSON(value.inductionClass),
        'role': value.role,
    };
}

/**
* @export
* @enum {string}
*/
export enum AppUserProfileResponseRoleEnum {
    Admin = 'admin',
    Officer = 'officer',
    Member = 'member',
    Inductee = 'inductee',
    Guest = 'guest'
}


