/* tslint:disable */
/* eslint-disable */
/**
 * HKN API 
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppUserRolesResponse
 */
export interface AppUserRolesResponse {
    /**
     * 
     * @type {string}
     * @memberof AppUserRolesResponse
     */
    role: AppUserRolesResponseRoleEnum;
}

export function AppUserRolesResponseFromJSON(json: any): AppUserRolesResponse {
    return AppUserRolesResponseFromJSONTyped(json, false);
}

export function AppUserRolesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppUserRolesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'role': json['role'],
    };
}

export function AppUserRolesResponseToJSON(value?: AppUserRolesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role': value.role,
    };
}

/**
* @export
* @enum {string}
*/
export enum AppUserRolesResponseRoleEnum {
    Admin = 'admin',
    Officer = 'officer',
    Member = 'member',
    Inductee = 'inductee',
    Guest = 'guest'
}


