/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AppUserNameResponse
 */
export interface AppUserNameResponse {
  /**
   *
   * @type {number}
   * @memberof AppUserNameResponse
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof AppUserNameResponse
   */
  firstName: string;
  /**
   *
   * @type {string}
   * @memberof AppUserNameResponse
   */
  lastName: string;
}

export function AppUserNameResponseFromJSON(json: any): AppUserNameResponse {
  return AppUserNameResponseFromJSONTyped(json, false);
}

export function AppUserNameResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AppUserNameResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    firstName: json['firstName'],
    lastName: json['lastName'],
  };
}

export function AppUserNameResponseToJSON(
  value?: AppUserNameResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    firstName: value.firstName,
    lastName: value.lastName,
  };
}
