/* tslint:disable */
/* eslint-disable */
/**
 * HKN API 
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttendanceResponse
 */
export interface AttendanceResponse {
    /**
     * 
     * @type {any}
     * @memberof AttendanceResponse
     */
    attendee: any | null;
    /**
     * 
     * @type {any}
     * @memberof AttendanceResponse
     */
    event: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof AttendanceResponse
     */
    isInductee: boolean;
    /**
     * 
     * @type {any}
     * @memberof AttendanceResponse
     */
    officer?: any | null;
    /**
     * 
     * @type {string}
     * @memberof AttendanceResponse
     */
    startTime: string;
    /**
     * 
     * @type {string}
     * @memberof AttendanceResponse
     */
    endTime?: string;
    /**
     * 
     * @type {number}
     * @memberof AttendanceResponse
     */
    points?: number;
}

export function AttendanceResponseFromJSON(json: any): AttendanceResponse {
    return AttendanceResponseFromJSONTyped(json, false);
}

export function AttendanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttendanceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attendee': json['attendee'],
        'event': json['event'],
        'isInductee': json['isInductee'],
        'officer': !exists(json, 'officer') ? undefined : json['officer'],
        'startTime': json['startTime'],
        'endTime': !exists(json, 'endTime') ? undefined : json['endTime'],
        'points': !exists(json, 'points') ? undefined : json['points'],
    };
}

export function AttendanceResponseToJSON(value?: AttendanceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attendee': value.attendee,
        'event': value.event,
        'isInductee': value.isInductee,
        'officer': value.officer,
        'startTime': value.startTime,
        'endTime': value.endTime,
        'points': value.points,
    };
}


