/* tslint:disable */
/* eslint-disable */
/**
 * HKN API 
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttendanceCheckOffRequest
 */
export interface AttendanceCheckOffRequest {
    /**
     * 
     * @type {number}
     * @memberof AttendanceCheckOffRequest
     */
    attendeeId: number;
}

export function AttendanceCheckOffRequestFromJSON(json: any): AttendanceCheckOffRequest {
    return AttendanceCheckOffRequestFromJSONTyped(json, false);
}

export function AttendanceCheckOffRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttendanceCheckOffRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attendeeId': json['attendeeId'],
    };
}

export function AttendanceCheckOffRequestToJSON(value?: AttendanceCheckOffRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attendeeId': value.attendeeId,
    };
}


