/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface InducteePointsResponse
 */
export interface InducteePointsResponse {
  /**
   *
   * @type {number}
   * @memberof InducteePointsResponse
   */
  user: number;
  /**
   *
   * @type {string}
   * @memberof InducteePointsResponse
   */
  email: string;
  /**
   *
   * @type {number}
   * @memberof InducteePointsResponse
   */
  points: number;
  /**
   *
   * @type {boolean}
   * @memberof InducteePointsResponse
   */
  hasProfessionalRequirement: boolean;
  /**
   *
   * @type {boolean}
   * @memberof InducteePointsResponse
   */
  hasMentorshipRequirement: boolean;
}

export function InducteePointsResponseFromJSON(
  json: any
): InducteePointsResponse {
  return InducteePointsResponseFromJSONTyped(json, false);
}

export function InducteePointsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InducteePointsResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    user: json['user'],
    email: json['email'],
    points: json['points'],
    hasProfessionalRequirement: json['hasProfessionalRequirement'],
    hasMentorshipRequirement: json['hasMentorshipRequirement'],
  };
}

export function InducteePointsResponseToJSON(
  value?: InducteePointsResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user: value.user,
    email: value.email,
    points: value.points,
    hasProfessionalRequirement: value.hasProfessionalRequirement,
    hasMentorshipRequirement: value.hasMentorshipRequirement,
  };
}
