/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface InterviewWeekStartDate
 */
export interface InterviewWeekStartDate {
  /**
   *
   * @type {string}
   * @memberof InterviewWeekStartDate
   */
  startDate: string;
}

export function InterviewWeekStartDateFromJSON(
  json: any
): InterviewWeekStartDate {
  return InterviewWeekStartDateFromJSONTyped(json, false);
}

export function InterviewWeekStartDateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InterviewWeekStartDate {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    startDate: json['startDate'],
  };
}

export function InterviewWeekStartDateToJSON(
  value?: InterviewWeekStartDate | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    startDate: value.startDate,
  };
}
