/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  InterviewWeekStartDate,
  InterviewWeekStartDateFromJSON,
  InterviewWeekStartDateFromJSONTyped,
  InterviewWeekStartDateToJSON,
} from './';

/**
 *
 * @export
 * @interface InterviewDatesResponse
 */
export interface InterviewDatesResponse {
  /**
   *
   * @type {Array<InterviewWeekStartDate>}
   * @memberof InterviewDatesResponse
   */
  interviewWeeks: Array<InterviewWeekStartDate>;
}

export function InterviewDatesResponseFromJSON(
  json: any
): InterviewDatesResponse {
  return InterviewDatesResponseFromJSONTyped(json, false);
}

export function InterviewDatesResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InterviewDatesResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    interviewWeeks: (json['interviewWeeks'] as Array<any>).map(
      InterviewWeekStartDateFromJSON
    ),
  };
}

export function InterviewDatesResponseToJSON(
  value?: InterviewDatesResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    interviewWeeks: (value.interviewWeeks as Array<any>).map(
      InterviewWeekStartDateToJSON
    ),
  };
}
