/* tslint:disable */
/* eslint-disable */
/**
 * HKN API 
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MultipleAttendanceQuery
 */
export interface MultipleAttendanceQuery {
    /**
     * 
     * @type {boolean}
     * @memberof MultipleAttendanceQuery
     */
    unchecked?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MultipleAttendanceQuery
     */
    inductee?: boolean;
}

export function MultipleAttendanceQueryFromJSON(json: any): MultipleAttendanceQuery {
    return MultipleAttendanceQueryFromJSONTyped(json, false);
}

export function MultipleAttendanceQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultipleAttendanceQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'unchecked': !exists(json, 'unchecked') ? undefined : json['unchecked'],
        'inductee': !exists(json, 'inductee') ? undefined : json['inductee'],
    };
}

export function MultipleAttendanceQueryToJSON(value?: MultipleAttendanceQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'unchecked': value.unchecked,
        'inductee': value.inductee,
    };
}


