/* tslint:disable */
/* eslint-disable */
/**
 * HKN API 
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MultipleUserQuery
 */
export interface MultipleUserQuery {
    /**
     * 
     * @type {boolean}
     * @memberof MultipleUserQuery
     */
    officers?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MultipleUserQuery
     */
    names?: boolean;
}

export function MultipleUserQueryFromJSON(json: any): MultipleUserQuery {
    return MultipleUserQueryFromJSONTyped(json, false);
}

export function MultipleUserQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultipleUserQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'officers': !exists(json, 'officers') ? undefined : json['officers'],
        'names': !exists(json, 'names') ? undefined : json['names'],
    };
}

export function MultipleUserQueryToJSON(value?: MultipleUserQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'officers': value.officers,
        'names': value.names,
    };
}


