/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  InducteePointsResponse,
  InducteePointsResponseFromJSON,
  InducteePointsResponseFromJSONTyped,
  InducteePointsResponseToJSON,
} from './';

/**
 *
 * @export
 * @interface MultipleInducteePointsResponse
 */
export interface MultipleInducteePointsResponse {
  /**
   *
   * @type {Array<InducteePointsResponse>}
   * @memberof MultipleInducteePointsResponse
   */
  inducteePoints: Array<InducteePointsResponse>;
}

export function MultipleInducteePointsResponseFromJSON(
  json: any
): MultipleInducteePointsResponse {
  return MultipleInducteePointsResponseFromJSONTyped(json, false);
}

export function MultipleInducteePointsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MultipleInducteePointsResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    inducteePoints: (json['inducteePoints'] as Array<any>).map(
      InducteePointsResponseFromJSON
    ),
  };
}

export function MultipleInducteePointsResponseToJSON(
  value?: MultipleInducteePointsResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    inducteePoints: (value.inducteePoints as Array<any>).map(
      InducteePointsResponseToJSON
    ),
  };
}
