/* tslint:disable */
/* eslint-disable */
/**
 * HKN API 
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AppUserResponse,
    AppUserResponseFromJSON,
    AppUserResponseFromJSONTyped,
    AppUserResponseToJSON,
} from './';

/**
 * 
 * @export
 * @interface MultipleAppUserResponse
 */
export interface MultipleAppUserResponse {
    /**
     * 
     * @type {Array<AppUserResponse>}
     * @memberof MultipleAppUserResponse
     */
    users: Array<AppUserResponse>;
}

export function MultipleAppUserResponseFromJSON(json: any): MultipleAppUserResponse {
    return MultipleAppUserResponseFromJSONTyped(json, false);
}

export function MultipleAppUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultipleAppUserResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'users': ((json['users'] as Array<any>).map(AppUserResponseFromJSON)),
    };
}

export function MultipleAppUserResponseToJSON(value?: MultipleAppUserResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'users': ((value.users as Array<any>).map(AppUserResponseToJSON)),
    };
}


