/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  RSVPResponse,
  RSVPResponseFromJSON,
  RSVPResponseFromJSONTyped,
  RSVPResponseToJSON,
} from './';

/**
 *
 * @export
 * @interface MultipleRSVPResponse
 */
export interface MultipleRSVPResponse {
  /**
   *
   * @type {Array<RSVPResponse>}
   * @memberof MultipleRSVPResponse
   */
  rsvps: Array<RSVPResponse>;
}

export function MultipleRSVPResponseFromJSON(json: any): MultipleRSVPResponse {
  return MultipleRSVPResponseFromJSONTyped(json, false);
}

export function MultipleRSVPResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MultipleRSVPResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    rsvps: (json['rsvps'] as Array<any>).map(RSVPResponseFromJSON),
  };
}

export function MultipleRSVPResponseToJSON(
  value?: MultipleRSVPResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    rsvps: (value.rsvps as Array<any>).map(RSVPResponseToJSON),
  };
}
