/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MultipleEventQuery
 */
export interface MultipleEventQuery {
  /**
   *
   * @type {boolean}
   * @memberof MultipleEventQuery
   */
  pending?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof MultipleEventQuery
   */
  ready?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof MultipleEventQuery
   */
  complete?: boolean;
}

export function MultipleEventQueryFromJSON(json: any): MultipleEventQuery {
  return MultipleEventQueryFromJSONTyped(json, false);
}

export function MultipleEventQueryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MultipleEventQuery {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    pending: !exists(json, 'pending') ? undefined : json['pending'],
    ready: !exists(json, 'ready') ? undefined : json['ready'],
    complete: !exists(json, 'complete') ? undefined : json['complete'],
  };
}

export function MultipleEventQueryToJSON(
  value?: MultipleEventQuery | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    pending: value.pending,
    ready: value.ready,
    complete: value.complete,
  };
}
