/* tslint:disable */
/* eslint-disable */
/**
 * HKN API 
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AppUserEventResponse,
    AppUserEventResponseFromJSON,
    AppUserEventResponseFromJSONTyped,
    AppUserEventResponseToJSON,
    EventRSVPResponse,
    EventRSVPResponseFromJSON,
    EventRSVPResponseFromJSONTyped,
    EventRSVPResponseToJSON,
} from './';

/**
 * 
 * @export
 * @interface RSVPResponse
 */
export interface RSVPResponse {
    /**
     * 
     * @type {EventRSVPResponse}
     * @memberof RSVPResponse
     */
    event: EventRSVPResponse;
    /**
     * 
     * @type {AppUserEventResponse}
     * @memberof RSVPResponse
     */
    appUser: AppUserEventResponse;
}

export function RSVPResponseFromJSON(json: any): RSVPResponse {
    return RSVPResponseFromJSONTyped(json, false);
}

export function RSVPResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RSVPResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'event': EventRSVPResponseFromJSON(json['event']),
        'appUser': AppUserEventResponseFromJSON(json['appUser']),
    };
}

export function RSVPResponseToJSON(value?: RSVPResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'event': EventRSVPResponseToJSON(value.event),
        'appUser': AppUserEventResponseToJSON(value.appUser),
    };
}


