export const RESUME = 'resume'
export const PROFILE = 'profile'
//export const FBPAGE = 'fb-page'
export const TOTPOINT = 'totalpoints'
export const EVENTS = 'events-page'
export const POINTS = 'points'