// export const LANDING = '/'
export const SIGN_UP = '/signup';
export const SIGN_IN = '/login';
export const CALENDAR = '/calendar';
export const HOME = '/';
export const EVENTS = '/events';
export const POINTS = '/points';
export const RESUME = '/resume';
export const INDUCTEES = '/inductees';
