/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  InterviewDatesResponse,
  InterviewDatesResponseFromJSON,
  InterviewDatesResponseToJSON,
} from '../models';

export interface InductionClassControllerGetInterviewDatesRequest {
  inductionClassID: string;
}

/**
 *
 */
export class InductionClassApi extends runtime.BaseAPI {
  /**
   * Get interview dates
   */
  async inductionClassControllerGetInterviewDatesRaw(
    requestParameters: InductionClassControllerGetInterviewDatesRequest
  ): Promise<runtime.ApiResponse<InterviewDatesResponse>> {
    if (
      requestParameters.inductionClassID === null ||
      requestParameters.inductionClassID === undefined
    ) {
      throw new runtime.RequiredError(
        'inductionClassID',
        'Required parameter requestParameters.inductionClassID was null or undefined when calling inductionClassControllerGetInterviewDates.'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request({
      path: `/api/inductionclass/{inductionClassID}/interviewdates`.replace(
        `{${'inductionClassID'}}`,
        encodeURIComponent(String(requestParameters.inductionClassID))
      ),
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    });

    return new runtime.JSONApiResponse(response, jsonValue =>
      InterviewDatesResponseFromJSON(jsonValue)
    );
  }

  /**
   * Get interview dates
   */
  async inductionClassControllerGetInterviewDates(
    requestParameters: InductionClassControllerGetInterviewDatesRequest
  ): Promise<InterviewDatesResponse> {
    const response = await this.inductionClassControllerGetInterviewDatesRaw(
      requestParameters
    );
    return await response.value();
  }
}
