/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  AppUserProfileResponse,
  AppUserProfileResponseFromJSON,
  AppUserProfileResponseToJSON,
  AppUserRolesResponse,
  AppUserRolesResponseFromJSON,
  AppUserRolesResponseToJSON,
} from '../models';

export interface UserControllerGetUserProfileRequest {
  userID: number;
}

export interface UserControllerGetUserRoleRequest {
  userID: number;
}

/**
 *
 */
export class UserApi extends runtime.BaseAPI {
  /**
   * Get user profile
   */
  async userControllerGetUserProfileRaw(
    requestParameters: UserControllerGetUserProfileRequest
  ): Promise<runtime.ApiResponse<AppUserProfileResponse>> {
    if (
      requestParameters.userID === null ||
      requestParameters.userID === undefined
    ) {
      throw new runtime.RequiredError(
        'userID',
        'Required parameter requestParameters.userID was null or undefined when calling userControllerGetUserProfile.'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request({
      path: `/api/users/{userID}`.replace(
        `{${'userID'}}`,
        encodeURIComponent(String(requestParameters.userID))
      ),
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    });

    return new runtime.JSONApiResponse(response, jsonValue =>
      AppUserProfileResponseFromJSON(jsonValue)
    );
  }

  /**
   * Get user profile
   */
  async userControllerGetUserProfile(
    requestParameters: UserControllerGetUserProfileRequest
  ): Promise<AppUserProfileResponse> {
    const response = await this.userControllerGetUserProfileRaw(
      requestParameters
    );
    return await response.value();
  }

  /**
   * Get user role
   */
  async userControllerGetUserRoleRaw(
    requestParameters: UserControllerGetUserRoleRequest
  ): Promise<runtime.ApiResponse<AppUserRolesResponse>> {
    if (
      requestParameters.userID === null ||
      requestParameters.userID === undefined
    ) {
      throw new runtime.RequiredError(
        'userID',
        'Required parameter requestParameters.userID was null or undefined when calling userControllerGetUserRole.'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString =
        typeof token === 'function' ? token('TokenAuth', []) : token;

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request({
      path: `/api/users/{userID}/roles`.replace(
        `{${'userID'}}`,
        encodeURIComponent(String(requestParameters.userID))
      ),
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    });

    return new runtime.JSONApiResponse(response, jsonValue =>
      AppUserRolesResponseFromJSON(jsonValue)
    );
  }

  /**
   * Get user role
   */
  async userControllerGetUserRole(
    requestParameters: UserControllerGetUserRoleRequest
  ): Promise<AppUserRolesResponse> {
    const response = await this.userControllerGetUserRoleRaw(requestParameters);
    return await response.value();
  }
}
