/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  AppUserEventResponse,
  AppUserEventResponseFromJSON,
  AppUserEventResponseFromJSONTyped,
  AppUserEventResponseToJSON,
  EventAttendanceResponse,
  EventAttendanceResponseFromJSON,
  EventAttendanceResponseFromJSONTyped,
  EventAttendanceResponseToJSON,
} from './';

/**
 *
 * @export
 * @interface AttendanceResponse
 */
export interface AttendanceResponse {
  /**
   *
   * @type {AppUserEventResponse}
   * @memberof AttendanceResponse
   */
  attendee: AppUserEventResponse;
  /**
   *
   * @type {EventAttendanceResponse}
   * @memberof AttendanceResponse
   */
  event: EventAttendanceResponse;
  /**
   *
   * @type {boolean}
   * @memberof AttendanceResponse
   */
  isInductee: boolean;
  /**
   *
   * @type {AppUserEventResponse}
   * @memberof AttendanceResponse
   */
  officer?: AppUserEventResponse;
  /**
   *
   * @type {number}
   * @memberof AttendanceResponse
   */
  duration?: number;
}

export function AttendanceResponseFromJSON(json: any): AttendanceResponse {
  return AttendanceResponseFromJSONTyped(json, false);
}

export function AttendanceResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AttendanceResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    attendee: AppUserEventResponseFromJSON(json['attendee']),
    event: EventAttendanceResponseFromJSON(json['event']),
    isInductee: json['isInductee'],
    officer: !exists(json, 'officer')
      ? undefined
      : AppUserEventResponseFromJSON(json['officer']),
    duration: !exists(json, 'duration') ? undefined : json['duration'],
  };
}

export function AttendanceResponseToJSON(
  value?: AttendanceResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    attendee: AppUserEventResponseToJSON(value.attendee),
    event: EventAttendanceResponseToJSON(value.event),
    isInductee: value.isInductee,
    officer: AppUserEventResponseToJSON(value.officer),
    duration: value.duration,
  };
}
