/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EventRSVPResponse
 */
export interface EventRSVPResponse {
  /**
   *
   * @type {Array<any>}
   * @memberof EventRSVPResponse
   */
  hosts: Array<any>;
  /**
   *
   * @type {string}
   * @memberof EventRSVPResponse
   */
  status: EventRSVPResponseStatusEnum;
  /**
   *
   * @type {string}
   * @memberof EventRSVPResponse
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof EventRSVPResponse
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof EventRSVPResponse
   */
  location?: string;
  /**
   *
   * @type {string}
   * @memberof EventRSVPResponse
   */
  startDate: string;
  /**
   *
   * @type {string}
   * @memberof EventRSVPResponse
   */
  endDate: string;
  /**
   *
   * @type {string}
   * @memberof EventRSVPResponse
   */
  type?: EventRSVPResponseTypeEnum;
  /**
   *
   * @type {string}
   * @memberof EventRSVPResponse
   */
  fbURL?: string;
  /**
   *
   * @type {string}
   * @memberof EventRSVPResponse
   */
  canvaURL?: string;
}

export function EventRSVPResponseFromJSON(json: any): EventRSVPResponse {
  return EventRSVPResponseFromJSONTyped(json, false);
}

export function EventRSVPResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventRSVPResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    hosts: json['hosts'],
    status: json['status'],
    name: json['name'],
    description: json['description'],
    location: !exists(json, 'location') ? undefined : json['location'],
    startDate: json['startDate'],
    endDate: json['endDate'],
    type: !exists(json, 'type') ? undefined : json['type'],
    fbURL: !exists(json, 'fbURL') ? undefined : json['fbURL'],
    canvaURL: !exists(json, 'canvaURL') ? undefined : json['canvaURL'],
  };
}

export function EventRSVPResponseToJSON(value?: EventRSVPResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    hosts: value.hosts,
    status: value.status,
    name: value.name,
    description: value.description,
    location: value.location,
    startDate: value.startDate,
    endDate: value.endDate,
    type: value.type,
    fbURL: value.fbURL,
    canvaURL: value.canvaURL,
  };
}

/**
 * @export
 * @enum {string}
 */
export enum EventRSVPResponseStatusEnum {
  Pending = 'pending',
  Ready = 'ready',
  Complete = 'complete',
}
/**
 * @export
 * @enum {string}
 */
export enum EventRSVPResponseTypeEnum {
  Professional = 'professional',
  Social = 'social',
  Technical = 'technical',
  Mentorship = 'mentorship',
}
