/* tslint:disable */
/* eslint-disable */
/**
 * HKN API
 * HKN API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EventResponse
 */
export interface EventResponse {
  /**
   *
   * @type {number}
   * @memberof EventResponse
   */
  id: number;
  /**
   *
   * @type {Array<any>}
   * @memberof EventResponse
   */
  hosts: Array<any>;
  /**
   *
   * @type {string}
   * @memberof EventResponse
   */
  rsvpURL: string;
  /**
   *
   * @type {string}
   * @memberof EventResponse
   */
  signInURL: string;
  /**
   *
   * @type {string}
   * @memberof EventResponse
   */
  status: EventResponseStatusEnum;
  /**
   *
   * @type {string}
   * @memberof EventResponse
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof EventResponse
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof EventResponse
   */
  location?: string;
  /**
   *
   * @type {string}
   * @memberof EventResponse
   */
  startDate: string;
  /**
   *
   * @type {string}
   * @memberof EventResponse
   */
  endDate: string;
  /**
   *
   * @type {string}
   * @memberof EventResponse
   */
  type?: EventResponseTypeEnum;
  /**
   *
   * @type {string}
   * @memberof EventResponse
   */
  fbURL?: string;
  /**
   *
   * @type {string}
   * @memberof EventResponse
   */
  canvaURL?: string;
}

export function EventResponseFromJSON(json: any): EventResponse {
  return EventResponseFromJSONTyped(json, false);
}

export function EventResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    hosts: json['hosts'],
    rsvpURL: json['rsvpURL'],
    signInURL: json['signInURL'],
    status: json['status'],
    name: json['name'],
    description: json['description'],
    location: !exists(json, 'location') ? undefined : json['location'],
    startDate: json['startDate'],
    endDate: json['endDate'],
    type: !exists(json, 'type') ? undefined : json['type'],
    fbURL: !exists(json, 'fbURL') ? undefined : json['fbURL'],
    canvaURL: !exists(json, 'canvaURL') ? undefined : json['canvaURL'],
  };
}

export function EventResponseToJSON(value?: EventResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    hosts: value.hosts,
    rsvpURL: value.rsvpURL,
    signInURL: value.signInURL,
    status: value.status,
    name: value.name,
    description: value.description,
    location: value.location,
    startDate: value.startDate,
    endDate: value.endDate,
    type: value.type,
    fbURL: value.fbURL,
    canvaURL: value.canvaURL,
  };
}

/**
 * @export
 * @enum {string}
 */
export enum EventResponseStatusEnum {
  Pending = 'pending',
  Ready = 'ready',
  Complete = 'complete',
}
/**
 * @export
 * @enum {string}
 */
export enum EventResponseTypeEnum {
  Professional = 'professional',
  Social = 'social',
  Technical = 'technical',
  Mentorship = 'mentorship',
}
